### ISSUE TITLE
Can't update to 5.0.7

### ISSUE THREAD

**Issue by exaware** [iobroker-community-adapters/ioBroker.ring#614]
A few days ago I could update from v3.2.2 to v5.0.6 without problems. Than I went back to 3.2.2 again, because I got to much motions events with v5.0.6.
Today I found the reason (#602) for the multiple motion events and I wanted to test it again with 5.0.7. But after update the ring adapter doesn't get green and I get the error below. After this something in the system is damaged because even after installation of v3.2.2 the adapter doesn't get green and the same error comes. To fix the problem I have to restore my VM from a backup.

node.js: 18.18.2
js.controller: 5.0.12
npm 10.2.1

<html>
<body>

host.ioBroker | 2023-11-05 02:21:22.977 | error | Caught by controller[0]: Node.js v18.18.2
-- | -- | -- | --
host.ioBroker | 2023-11-05 02:21:22.977 | error | Caught by controller[0]: requestPath: '@homebridge/camera-utils'
host.ioBroker | 2023-11-05 02:21:22.977 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.ioBroker | 2023-11-05 02:21:22.977 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:119:18)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at Module._findPath (node:internal/modules/cjs/loader:680:18)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/@homebridge/camera-utils/lib/index.js'. Please verify that the package.json has a valid "main" entry
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: throw err;
host.ioBroker | 2023-11-05 02:21:22.977 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32) {
host.ioBroker | 2023-11-05 02:21:22.977 | error | Caught by controller[0]: path: '/opt/iobroker/node_modules/@homebridge/camera-utils/package.json',
host.ioBroker | 2023-11-05 02:21:22.977 | error | Caught by controller[0]: }
host.ioBroker | 2023-11-05 02:21:22.977 | error | instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: node:internal/modules/cjs/loader:446
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: ^
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at tryPackage (node:internal/modules/cjs/loader:438:19)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
host.ioBroker | 2023-11-05 02:21:22.976 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/ring-client-api/lib/streaming/streaming-session.js:5:24)

</body>
</html>

**Comment by dbuehl** [comment]
Hi,

I seem to have the same issue here. It first occured after updating my ioBroker from js-controller 4.0.24 to 5.0.12 and node.js from 18.17.1 to 18.18.2. Upon installation of ring adapter v5.0.7, As of then, my log file the same error as posted by exaware.

I looked as if it had to do with node.js 18.18.2, so I then reverted back to my previous installation with js-controller 4.0.24 and node.js. Adapter v3.4.0 ran fine here. As of updating from v3.4.0 to v5.0.7, I see the same errors. 

Log file also caught this, when the update process was invoked:

host.iobroker | 2023-11-05 12:58:42.556 | error | startInstance ring.0: cannot find start file!
-- | -- | -- | --
host.iobroker | 2023-11-05 12:58:12.425 | info | Restart adapter system.adapter.ring.0 because enabled
host.iobroker | 2023-11-05 12:58:12.424 | error | instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
ring.0 | 2023-11-05 12:58:11.765 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ring.0 | 2023-11-05 12:58:11.764 | info | terminating
ring.0 | 2023-11-05 12:58:11.752 | error | Exception-Code: ENOENT: spawn /opt/iobroker/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
ring.0 | 2023-11-05 12:58:11.752 | error | Error: spawn /opt/iobroker/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT at ChildProcess._handle.onexit (node:internal/child_process:283:19) at onErrorNT (node:internal/child_process:476:16) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ring.0 | 2023-11-05 12:58:11.747 | error | uncaught exception: spawn /opt/iobroker/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
host.iobroker | 2023-11-05 12:57:14.832 | info | iobroker Installing iobroker-community-adapters/ioBroker.ring... (System call)
host.iobroker | 2023-11-05 12:57:14.830 | info | iobroker NPM version: 9.6.7
host.iobroker | 2023-11-05 12:57:14.010 | info | iobroker install iobroker-community-adapters/ioBroker.ring
host.iobroker | 2023-11-05 12:57:11.819 | info | iobroker url iobroker-community-adapters/ioBroker.ring --host iobroker --debug

Is the adapter v5.0.7 missing some dependencies?

**Comment by dbuehl** [comment]
thanks, theimo, now that's what I call active development!

will check v5.0.8 tonight and report here

**Comment by mcm1957** [comment]
@theimo1221 

I've opened this issue some hours ago as there seems to be an inconsistency between package.json and existing files.
https://github.com/homebridge/camera-utils/issues/556

Not sure wether it really is a issue there - but I note it here for reference

**Comment by tsightler** [comment]
I don't believe that will fix it as the issue appears to be that the 2.2.1 version of the npm package is missing the /lib directory completely.  Temporary workaround is to continue to use 2.2.0 instead.  Hopefully the maintainers of camera-utils will fix the npm packages soon.

**Comment by exaware** [comment]
I tried again and have same problem with 5.0.8. I also installed 2.2.0 (npm install @homebridge/camera-utils@2.2.0) but this doesn't fix the problem. I don't know if the installation of 2.2.0 was successfull.
![image](https://github.com/iobroker-community-adapters/ioBroker.ring/assets/55593493/afeabffd-3919-459a-aa44-a9c58fb83db0)


<html>
<body>


host.ioBroker | 2023-11-05 19:20:02.359 | error | instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: Node.js v18.18.2
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: }
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: requestPath: '@homebridge/camera-utils'
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: path: '/opt/iobroker/node_modules/@homebridge/camera-utils/package.json',
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32) {
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/ring-client-api/lib/streaming/streaming-session.js:5:24)
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:119:18)
host.ioBroker | 2023-11-05 19:20:02.359 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: at Module._findPath (node:internal/modules/cjs/loader:680:18)
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: at tryPackage (node:internal/modules/cjs/loader:438:19)
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/@homebridge/camera-utils/lib/index.js'. Please verify that the package.json has a valid "main" entry
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: ^
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: throw err;
host.ioBroker | 2023-11-05 19:20:02.358 | error | Caught by controller[0]: node:internal/modules/cjs/loader:446


</body>
</html>

**Comment by exaware** [comment]
After I figured out that I have to install 2.2.0 into the folder '/opt/iobroker/node_modules/@homebridge', the installation was successfully and for now the problem is fixed.

**Comment by dbuehl** [comment]
I have updated to ring adapter v5.0.9 but this did not fix the problem.
Checked the version of @homebridge/camera-utils to find it still at 2.2.1. 

@exaware - can you please advise on how to downgrade to 2.2.0?

**Comment by exaware** [comment]
@dbuehl, open ssh console and navigate to:
'/opt/iobroker/node_modules/@homebridge'
and execute folowing command there:
'npm install @homebridge/camera-utils@2.2.0'

**Comment by dbuehl** [comment]
I uninstalled v5.0.9 again and manually deleted /opt/iobroker/node_modules/@homebridge/camera-utils.
Then reinstalled v5.0.9, adapter keeps running stable OK.

npm v @homebride/camera-utils still returns version 2.2.1 although v5.0.9 claims to install camera-util version 2.2.0

Works as should but feels but yet feels dodgy...

**Comment by donavanbecker** [comment]
v2.2.4 resolves this.

![image](https://github.com/homebridge/camera-utils/assets/9875439/431212fb-a79a-4919-be2b-cb5e3ed4038b)

**Comment by dbuehl** [comment]
My issues are resolved as of v5.0.10

@exaware - what about you? You raised the issue...

**Comment by exaware** [comment]
As I already wrote, manually installation of homebridge 2.2.0 instead of 2.2.1 in the correct path, fixed my problem. But just right now I installed v5.0.10 and it works for me too.
